version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
       - mvn clean install package
artifacts:
  files:
    - target/*.war
    - appspec.yml
  discard-paths: yes
