name: Build and Test

on:
  push:
    branches:
      - master
permissions: write-all
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3     
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mamathasama/javagithub:build-${{ github.run_number }}
        
        #run: |
         #   docker build -t mamathasama/javagithub:build-${{ github.run_number }} .
          #  docker push mamathasama/javagithub:build-${{ github.run_number }}
            
      - name: Checkout k8 manifests repo
        uses: actions/checkout@v2
        with:
          repository: mpakeeru/argo-cd
          ref: master  # Specify the branch or commit you want to checkout
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Edit deployment file and commit changes
        run: |
          # Update the file content
          sed -i 's|\(image:\) .*|\1 mamathasama/javagithub:build-${{ github.run_number }}|' tomcatwebapp-deployment.yml

          # Configure Git
          git config --global user.email "mamathasama@hotmail.com"
          git config --global user.name "mpakeeru"

          # Add and commit changes
          git add tomcatwebapp-deployment.yml
          git commit -m "Update image version wit ${{ github.run_number }} "
          git push




         
