name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      
      - name: Build and Push Image
        run: |
            docker build -t mamathasama/javagithub:build-${{ github.run_number }} .
            docker push mamathasama/javagithub:build-${{ github.run_number }}
      
      - name: Checkout k8 manifests repo
        uses: actions/checkout@v2
        with:
          repository: mpakeeru/argo-cd
          ref: master  # Specify the branch or commit you want to checkout
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit file and commit changes
        run: |
          # Update the file content
          sed -i 's|\(image:\) .*|\1 mamathasama/javagithub:build-${{ github.run_number }}|' tomcatwebapp-deployment.yml

          # Configure Git
          git config user.email "mamathasama@hotmail.com"
          git config user.name "mpakeeru"

          # Add and commit changes
          git add tomcatwebapp-deployment.yml
          git commit -m "Update image version wit ${{ github.run_number }} "

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: mpakeeru/argo-cd
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: master
         
