name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
     
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        run: mvn sonar:sonar -Dsonar.host.url=http://192.168.86.36:9000 -Dsonar.projectKey=github_actions
